<a href="https://colab.research.google.com/github/vrspi/Breast-Cancer-Wisconsin-Classifier/blob/main/Breast_Cancer_Wisconsin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libs

In [44]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [45]:
dataset = pd.read_csv("breast_cancer.csv")
X = dataset.iloc[:,1:-1].values
Y = dataset.iloc[:,-1].values

# DATA PREPROCESSING

In [46]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)


In [47]:
print(y_train[:10])

[4 2 2 2 4 2 2 2 2 4]


In [48]:
print(x_train[:10])

[[10  1  1  1  2 10  5  4  1]
 [ 1  1  1  1  1  1  3  1  1]
 [ 5  1  1  1  2  1  3  1  1]
 [ 3  1  2  1  2  1  2  1  1]
 [ 8  2  3  1  6  3  7  1  1]
 [ 1  1  1  1  2  1  3  1  1]
 [ 2  1  1  1  2  1  3  1  1]
 [ 4  1  1  3  1  1  2  1  1]
 [ 5  7  7  1  5  8  3  4  1]
 [ 8 10 10  8  6  9  3 10 10]]


# train model (Logistic Regression)

In [49]:
from sklearn.linear_model import LogisticRegression

Classifier = LogisticRegression(random_state=0)
Classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [50]:
Y_pred = Classifier.predict(x_test)

print(Y_pred)
print(y_test)

[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 4 4 2 4 2 4 4 2 4 4 4 4 2 2 2 4 4 2 2 4 2 2 2 4
 2 2 4 2 2 2 2 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2]
[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 2 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 2 4 2 4 2 4 4 4 2 4 4 4 2 2 2 4 4 2 2 4 4 2 2 4
 2 2 4 2 2 2 4 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2]


# Evaluate the model

In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix


cm = confusion_matrix(y_test,Y_pred,labels=[2,4])
print(cm)
accuracy_score(y_test,Y_pred)

[[84  3]
 [ 3 47]]


0.9562043795620438